#!/usr/bin/env bash
# BUG-005 structural audit: AES DATA_IN registers expose a software read path.
#
# The finding is established entirely from evidence inside the audited tree.
# DATA_IN is declared write-only in the RDL and instantiated SwAccessWO in the
# generated register block, yet the read multiplexer in that same file returns
# its stored contents. The file's other write-only register, TRIGGER, shows the
# correct treatment: its read arm returns constant zero. No external repository,
# reference revision, or expected-answer list is consulted anywhere below.
set -euo pipefail

CMP="${AUDIT_ROOT:-/home/smy/hackatdac26-phase-2-caliptra}"
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LOGS="$(cd "$HERE/../logs" && pwd)"
RUN_LOG="$LOGS/run.log"
WITNESS_LOG="$LOGS/witness.log"

: > "$RUN_LOG"
: > "$WITNESS_LOG"

F="src/aes/rtl/aes_reg_top.sv"
RDL="src/aes/data/aes.rdl"

pass=1
gate() {
  if eval "$1" >/dev/null 2>&1; then
    echo "gate_ok: $2" >> "$RUN_LOG"
  else
    echo "gate_fail: $2" >> "$RUN_LOG"
    pass=0
  fi
}
section() { printf '\n===== %s =====\n' "$1" >> "$WITNESS_LOG"; }

echo "BUG-005 structural audit (single-tree)" >> "$RUN_LOG"
echo "audit_root=$CMP" >> "$RUN_LOG"
echo "date=$(date -Is)" >> "$RUN_LOG"

# ---------- Witness ----------
section "the four DATA_IN read multiplexer arms ($F:1784-1790)"
grep -n "reg2hw.data_in\[.*\].q;" "$CMP/$F" >> "$WITNESS_LOG"

section "RDL declares DATA_IN write-only ($RDL:66-82)"
sed -n '66,70p' "$CMP/$RDL" >> "$WITNESS_LOG"
sed -n '80,82p' "$CMP/$RDL" >> "$WITNESS_LOG"

section "generated subreg instance for DATA_IN[0] ($F:715-721)"
sed -n '715,721p' "$CMP/$F" >> "$WITNESS_LOG"

section "in-tree control: TRIGGER is also SwAccessWO and its read arm returns zero ($F:1826-1831)"
sed -n '1826,1831p' "$CMP/$F" >> "$WITNESS_LOG"

# ---------- Gates: the read path exists and is not dead code ----------
LEAKS=$(grep -c "reg2hw.data_in\[.*\].q;" "$CMP/$F")
echo "data_in_read_arms=$LEAKS" >> "$RUN_LOG"
gate "test '$LEAKS' -eq 4" \
     "All 4 DATA_IN words are returned from the read multiplexer as reg2hw.data_in[i].q"
gate "grep -q 'addr_hit\[21\] = (reg_addr == AES_DATA_IN_0_OFFSET);' '$CMP/$F'" \
     "DATA_IN[0] has a live address decode, so the read path is reachable"
gate "grep -q 'AES_DATA_IN_0_OFFSET = 8.h 54' '$CMP/src/aes/rtl/aes_reg_pkg.sv'" \
     "DATA_IN[0] sits at a fixed MMIO offset (0x54)"

# ---------- Gates: the RTL contradicts its own generated declaration ----------
gate "sed -n '706,724p' '$CMP/$F' | grep -q 'SwAccess(caliptra_prim_subreg_pkg::SwAccessWO)'" \
     "DATA_IN[0] is instantiated SwAccessWO, i.e. write-only, in this same file"
gate "grep -q 'reg_rdata_next\[31:0\] = reg2hw.data_in\[0\].q;' '$CMP/$F'" \
     "Yet this same file returns DATA_IN[0] contents on a read: an intra-file contradiction"

# ---------- Gates: the RTL contradicts the RDL it declares itself generated from ----------
gate "sed -n '68p' '$CMP/$RDL' | grep -q 'sw = w;'" \
     "RDL: the DATA_IN field is declared sw = w, write-only with no software read"
gate "grep -q 'Register Top module auto-generated by' '$CMP/$F'" \
     "The register block declares itself auto-generated from that RDL, so the tree is self-inconsistent"

# ---------- Gates: in-tree control, the correct pattern is present in the same file ----------
# TRIGGER is the file's other write-only register. Its read arm returns zero for
# every bit. This establishes the intended treatment of a write-only window from
# inside the audited file, with no external comparison.
WO_COUNT=$(grep -c 'SwAccessWO' "$CMP/$F")
echo "swaccesswo_instances=$WO_COUNT" >> "$RUN_LOG"
gate "test '$WO_COUNT' -eq 8" \
     "The file contains 8 SwAccessWO field instances: the 4 DATA_IN words and the 4 TRIGGER bits"
gate "sed -n '1140,1150p' '$CMP/$F' | grep -q 'SwAccess(caliptra_prim_subreg_pkg::SwAccessWO)'" \
     "Control: u_trigger_start is also instantiated SwAccessWO"
gate "sed -n '1826,1831p' '$CMP/$F' | grep -q \"reg_rdata_next\[0\] = '0;\"" \
     "Control: the TRIGGER read arm returns constant zero, the correct treatment for a write-only window"
TRIG_ZEROS=$(sed -n '1826,1832p' "$CMP/$F" | grep -c "= '0;")
gate "test '$TRIG_ZEROS' -ge 4" \
     "Control: every TRIGGER bit reads back zero, so the pattern is applied consistently there"
gate "! grep -q 'reg_rdata_next\[31:0\] = reg2hw.trigger' '$CMP/$F'" \
     "Control: no TRIGGER read arm returns register contents, unlike DATA_IN"

# ---------- Gates: firmware reachability ----------
HDR="src/integration/rtl/caliptra_reg/caliptra_reg.h"
gate "grep -q 'CLP_AES_REG_DATA_IN_0  *(0x10011054)' '$CMP/$HDR'" \
     "DATA_IN[0] is exposed to firmware at 0x10011054 in the generated header"
gate "grep -q 'CLP_AES_REG_DATA_IN_3  *(0x10011060)' '$CMP/$HDR'" \
     "DATA_IN[3] is exposed to firmware at 0x10011060 in the generated header"

section "firmware header entries for DATA_IN"
grep -n "CLP_AES_REG_DATA_IN_[0-3] " "$CMP/$HDR" >> "$WITNESS_LOG"

# ---------- Gates: the plaintext is not cleared when the block is consumed ----------
gate "grep -q 'hw2reg.data_in\[i\].d  = prd_clearing_data\[i\];' '$CMP/src/aes/rtl/aes_core.sv'" \
     "The registers are overwritten with pseudo-random data only via the explicit clear path"
gate "grep -q 'data_in_we_o       = 1.b1;' '$CMP/src/aes/rtl/aes_control_fsm.sv'" \
     "That clear is asserted in the CTRL_CLEAR_I state, i.e. on the software clear trigger"

section "clear path: only the explicit trigger overwrites DATA_IN"
grep -n "hw2reg.data_in\[i\]" "$CMP/src/aes/rtl/aes_core.sv" >> "$WITNESS_LOG"
grep -n "data_in_new_d = data_in_load" "$CMP/src/aes/rtl/aes_control_fsm.sv" >> "$WITNESS_LOG"

section "audit gate results"
grep -E '^gate_' "$RUN_LOG" >> "$WITNESS_LOG"

total=$(grep -c '^gate_' "$RUN_LOG")
ok=$(grep -c '^gate_ok' "$RUN_LOG")
echo "structural_gates_passed=$ok/$total" >> "$RUN_LOG"
echo "structural_gates_passed=$ok/$total" >> "$WITNESS_LOG"

if [ "$pass" -eq 1 ]; then
  echo "RESULT: PASS - all structural gates confirm BUG-005" >> "$RUN_LOG"
  echo "result=PASS" >> "$RUN_LOG"
  echo "RESULT: PASS" >> "$WITNESS_LOG"
  exit 0
else
  echo "RESULT: FAIL - at least one structural gate did not hold" >> "$RUN_LOG"
  echo "result=FAIL" >> "$RUN_LOG"
  echo "RESULT: FAIL" >> "$WITNESS_LOG"
  exit 1
fi
